project:
  type: website
  output-dir: docs

website:
  title: "Cancer Deaths 2013-2023 Multnomah County"
  search: false
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd #person A
        text: Home
      - href: abstract.qmd #person B
        text: Abstract
      - href: background.qmd
        text: Background Information
      - href: aim.qmd
        text: Aim of Research
      - href: methods.qmd
        text: Methods
      - href: findings.qmd
        text: Findings
      - href: conclusion.qmd
        text: Conclusions

format:
  html:
    theme: slate
    css: style.css
    toc: true
    code-fold: true