project:
  type: website
  output-dir: docs

website:
  title: "Cancer Deaths 2013-2023 Multanoma County"
  search: false
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd #person A
        text: Home
      - href: abstract.qmd #person B
        text: Abstract

format:
  html:
    theme: slate
    css: style.css
    toc: true
    code-fold: true